spring:
  application:
    name: API-GATEWAY
    server:
         port : 8081
    spring:
  cloud:
    gateway:
      routes:
      - id: talathi-service
        uri: http://localhost:9090/
        predicates:
        - Path=/land/**
     

